export const advertisments = [
    {
        _type: 'cars',
        p1: 'Brand',
        p2: 'Year',
        p3: 'Fuel',
        p4: 'KmDriven',
        p5: 'Title',
        p6: 'Description',
        p7: 'Location',
        p8: 'Price',
    },
    {
        _type: 'properties',
        p1: 'Type',
        p2: 'Bedroom',
        p3: 'Bathroom',
        p4: 'Furnishing',
        p5: 'Area',
        p6: 'Maintenance',
        p7: 'FloorNo',
        p8: 'CarParking',
        p9: 'Facing',
        p10: 'Title',
        p11: 'Description',
        p12: 'Location',
        p13: 'Price',
    },
    {
        _type: 'mobile',
        p1: 'Brand',
        p2: 'Price',
        p3: 'HowMuchOld',
        p4: 'Title',
        p5: 'Description',
        p6: 'Location',
    },
    {
        _type: 'jobs',
        p1: 'Type',
        p2: 'SalaryRange',
        p3: 'Position',
        p4: 'Title',
        p5: 'Description',
        p6: 'Location',
        p8: 'Price',
    },
    {
        _type: 'bikes',
        p1: 'Type',
        p2: 'Brand',
        p3: 'Year',
        p4: 'Km',
        p5: 'Title',
        p6: 'Description',
        p7: 'Location',
        p8: 'Price',
    },
    {
        _type: 'electronics',
        p1: 'Type',
        p2: 'Brand',
        p3: 'Title',
        p4: 'Description',
        p5: 'Location',
        p6: 'Price',
    },
    {
        _type: 'tution',
        p1: 'Type',
        p2: 'Fees',
        p3: 'Title',
        p4: 'Description',
        p5: 'Location',
        p6: 'Price',
    },

]
