export const advertisments = [
    {
        _type: 'tolets',
        p1: 'type',
        p2: 'room',
        p3: 'floor',
        p4: 'furnished',
        p5: 'Title',
        p6: 'Description',
        p7: 'Location',
        p8: 'Price',
    },
    {
        _type: 'chef',
        p1: 'Type',
        p2: 'Title',
        p3: 'Description',
        p4: 'Location',
        p5: 'Price',
    },
    {
        _type: 'mobile',
        p1: 'Brand',
        p2: 'Price',
        p3: 'HowMuchOld',
        p4: 'Title',
        p5: 'Description',
        p6: 'Location',
    },
    {
        _type: 'jobs',
        p1: 'Type',
        p2: 'SalaryRange',
        p3: 'Position',
        p4: 'Title',
        p5: 'Description',
        p6: 'Location',
        p7: 'Price',
    },
    {
        _type: 'bikes',
        p1: 'Type',
        p2: 'Brand',
        p3: 'Year',
        p4: 'Km',
        p5: 'Title',
        p6: 'Description',
        p7: 'Location',
        p8: 'Price',
    },
    {
        _type: 'furniture',
        p1: 'Type',
        p2: 'Brand',
        p3: 'Title',
        p4: 'Description',
        p5: 'Location',
        p6: 'Price',
    },
    {
        _type: 'tution',
        p1: 'Type',
        p2: 'Fees',
        p3: 'Title',
        p4: 'Description',
        p5: 'Location',
        p6: 'Price',
    },

]
